### ISSUE TITLE
딥러닝 주식분석기 구현

### ISSUE THREAD

**Issue by wkghd1223** [wkghd1223/graduate#9]
- [x] 한 종목에 대한 프로토타입 구현

- [x] 프로토타입 구체화

- [ ] 요구사항에 맞는 여러종목에 대한 주식분석기 구현

- [x] 개발된 프로그램 임베딩
